name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses:  actions/setup-node@v2.1.2
        with: 
          node-version: 14.x
  
      - name: Install dependencies
        run: yarn
      
      - name: Run build
        run: yarn build
      
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_KEY }}
            port: ${{ secrets.SSH_PORT }}
            source: ".,!node_modules"
            target: "~/app/GoBarber-backend"  
              
      - name: Install dependencies on Digital Ocean
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_KEY }}
            port: ${{ secrets.SSH_PORT }}
            script: |
              cd ~/app/GoBarber-backend
              yarn

      - name: Run migrations on Digital Ocean
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_KEY }}
            port: ${{ secrets.SSH_PORT }}
            script: |
             cd ~/app/GoBarber-backend
             ./node_modules/.bin/typeorm migration:run


      - name: Restart node on Digital Ocean
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_KEY }}
            port: ${{ secrets.SSH_PORT }}
            script: pm2 restart gobarber-api
